import type { AuditReport } from '../../../packages/shared/src/types'

export const sampleReport: AuditReport = {
  id: 'bench_0420_demo',
  url: 'https://example.com/task-flow',
  startedAt: '2026-04-20T14:00:00.000Z',
  completedAt: '2026-04-20T14:00:18.000Z',
  score: 40,
  verdict: 'Fragile',
  criticalFailures: 2,
  silentFailures: 1,
  essentialActionSurvival: false,
  geminiStatus: 'attached',
  subscores: {
    essentialUtility: 25,
    failureClarity: 60,
    stateSurvival: 20,
    recovery: 90,
    localResilience: 85,
  },
  checks: [
    {
      id: 'offlineReload',
      name: 'Offline reload',
      status: 'warn',
      label: 'Recoverable',
      summary: 'The shell survives reload, but the working state degrades into a read-only shell with no reliable path back to task completion.',
      evidence: 'Application layout remained visible after offline reload, but primary task controls no longer restored a safe completion path.',
      recommendation: 'Surface degraded-mode messaging immediately and make the loss of utility explicit before the user attempts another action.',
    },
    {
      id: 'essentialUtility',
      name: 'Essential action survival',
      status: 'fail',
      label: 'Critical',
      summary: 'The primary workflow collapses when connectivity drops mid-task, even though the interface still looks partially active.',
      evidence: 'Submitting the task after a forced network interruption left controls interactive but never returned a trustworthy completion state.',
      recommendation: 'Preserve the primary task locally before network confirmation and expose a truthful fallback path when the network fails.',
    },
    {
      id: 'draftPersistence',
      name: 'Draft persistence',
      status: 'fail',
      label: 'Critical',
      summary: 'User-authored input is lost on refresh, forcing reconstruction of work after continuity breaks.',
      evidence: 'Refreshing the page after an interrupted session cleared the in-progress draft and returned the form in a blank state.',
      recommendation: 'Persist authorship state locally and restore it before any server reconciliation logic runs.',
    },
    {
      id: 'failureClarity',
      name: 'Failure clarity',
      status: 'warn',
      label: 'Recoverable',
      summary: 'The app exposes enough visible state to explain failure, but the current message still understates what is no longer safe to do.',
      evidence: 'The error copy acknowledges an interruption but does not explain whether the last action succeeded, failed, or needs reconstruction.',
      recommendation: 'State what failed, what was preserved, and what the user can still trust without requiring inference.',
    },
    {
      id: 'reconnect',
      name: 'Reconnect behavior',
      status: 'pass',
      label: 'Strong',
      summary: 'The app detects recovery quickly and resumes network awareness without a full reload.',
      evidence: 'Reconnect state became visible after service restoration and the shell resumed polling without locking the interface.',
      recommendation: 'Keep reconnect handling, but pair it with more honest messaging about which task state was or was not restored.',
    },
    {
      id: 'lowBandwidth',
      name: 'Low-bandwidth posture',
      status: 'warn',
      label: 'Recoverable',
      summary: 'The interface remains usable under slow conditions, but loading behavior still suggests a healthier state than the system can support.',
      evidence: 'Key surfaces rendered under throttling, but latency masked failure boundaries and encouraged repeated submissions.',
      recommendation: 'Separate degraded progress states from normal readiness so slow mode does not impersonate full reliability.',
    },
    {
      id: 'localAuthorityHint',
      name: 'Local authority hint',
      status: 'pass',
      label: 'Strong',
      summary: 'The shell retains enough local structure to orient the user after interruption.',
      evidence: 'Navigation, recent context, and partial structural cues remained visible without network confirmation.',
      recommendation: 'Use this surviving structure to anchor degraded-mode instructions and recovery steps.',
    },
    {
      id: 'spinnerAbuse',
      name: 'Spinner abuse',
      status: 'fail',
      label: 'Silent',
      summary: 'Retry language implies recovery, but the system returns to ambiguous waiting without restoring actual utility.',
      evidence: 'The retry path re-entered a loading state and exposed no trustworthy confirmation that the task state was complete or recoverable.',
      recommendation: 'Make retry semantics honest about what was restored and provide a hard fallback when full readiness is unavailable.',
    },
  ],
  gemini: {
    summary: 'This app is optimized for continuity theater rather than continuity survival. The shell stays visible longer than the core task remains trustworthy.',
    priorities: [
      'Preserve primary task state locally before network confirmation.',
      'Surface degraded-mode messaging the moment continuity breaks.',
      'Decouple export and recovery paths from full application readiness.',
      'Make retry semantics explicit about what was and was not restored.',
    ],
    whyThisMatters: 'This is not a cosmetic failure. The interface keeps the shell alive while the user’s real ability to finish the task, recover their work, or trust the current state collapses underneath it.',
  },
}
